matrix:
  include:
    - language: python
      python:
        - "3.8"
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U pytest
        - pip install pytest-cov
        - cd python
      install:
        - pip install .
      script:
        - pytest -vv --cov=milisp tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: go
      go:
        - "1.13.x"
      before_install:
        - cd go
      script:
        - go test -v -coverprofile=coverage.txt -covermode=atomic ./milisp/...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
