matrix:
  include:
    - language: python
      python:
        - "3.8"
      before_install:
        - python --version
        - pip list
        - pip install -U pip
        - pip install -U pylint
        - pip install -U pytest
        - pip install -U pytest-cov
        - cd python
      install:
        - pip install .
      script:
        - pylint --rcfile pylintrc milisp
        - pylint --rcfile pylintrc tests/*
        - pylint --rcfile pylintrc-examples examples
        - pytest -vv examples  # it is not true tests; just check examples are runable
        - pytest -vv --cov=milisp tests
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: go
      go:
        - "1.15"
      before_install:
        - cd go
      script:
        - go test -v -coverprofile=coverage.txt -covermode=atomic ./milisp/...
      after_success:
        - bash <(curl -s https://codecov.io/bash)
