linters-settings:
  lll:
    line-length: 120
  funlen:
    lines: 100
    statements: 60
  cyclop:
    max-complexity: 30
linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
      # disabled by default
      # TODO: check desabled
    - asciicheck
    - cyclop
    - durationcheck
      # - errorlint
      # - exhaustivestruct
    - forbidigo
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godot
    - godox
      # - goerr113
    - gofumpt
    - goheader
      # - gomnd
    - gomoddirectives
    - gomodguard
    - importas
    - makezero
    - nestif
    - nilerr
      # - nlreturn
      # - paralleltest
    - prealloc
    - predeclared
    - revive
    - sqlclosecheck
      # - testpackage
    - thelper
    - tparallel
    - wastedassign
      # - wrapcheck
      # - wsl
